apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-5tfyt6y3egv3jgu3te37gbh3uygdy37gyd3ge3iujei3n
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          name: guestbook-ui
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlpwd
                  key: password
